services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - event-service
    environment:
      - USER_SERVICE_URL=http://user-service:4001
    env_file:
      - .env
    volumes:
      - ./services/api-gateway:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 3000 --reload

  user-service:
    build: ./services/user-service
    ports:
      - "4001:4001"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
      - MONGO_DB=users_db
    env_file:
      - .env
    volumes:
      - ./services/user-service:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 4001 --reload

  event-service:
    build: ./services/event-service
    ports:
      - "4003:4003"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
      - MONGO_DB=users_db
    env_file:
      - .env
    volumes:
      - ./services/event-service:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 4003 --reload

  notification-service:
    build: ./services/notification-service
    ports:
      - "4004:4004"
    depends_on:
      - mongo
      - user-service
      - event-service
    environment:
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
      - MONGO_DB=users_db
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json
      - EVENTOS_URL=http://event-service:4003
      - USUARIOS_URL=http://user-service:4001
    env_file:
      - .env
    volumes:
      - ./services/notification-service:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 4004 --reload

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
